# Generated by Django 5.1.5 on 2025-04-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalmessage',
            name='subject',
            field=models.TextField(),
        ),
    ]
