# Generated by Django 5.1.5 on 2025-05-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_group_groupmember_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='project.profile'),
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
    ]
