# Generated by Django 5.1.5 on 2025-05-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_friend_profile1_alter_friend_profile2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', to='project.profile'),
        ),
    ]
