# Generated by Django 5.1.5 on 2025-05-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
